#!/usr/bin/env python3
"""
Export database schema and configuration tables (no scan data).

This creates a SQL dump with:
- Full schema (CREATE TABLE statements)
- Config tables: model_configs, scan_profiles, profile_analyzers, profile_verifiers,
  static_rules, tuning_prompt_templates, tuning_test_cases, users, etc.
- NO scan data: scans, draft_findings, verified_findings, findings, etc.
"""

import sys
import os
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from app.core.database import engine
import sqlite3

# Tables to include (config/setup only, no scan results)
CONFIG_TABLES = [
    'model_configs',
    'scan_profiles',
    'profile_analyzers',
    'profile_verifiers',
    'static_rules',
    'vulnerability_categories',
    'tuning_prompt_templates',
    'tuning_test_cases',
    'users',
    'gitlab_repos',
    'github_repos',
    'repo_watchers',
    'output_templates',
]

def export_schema_and_config(output_file='backend/init_db.sql'):
    """Export schema and config tables to SQL file"""

    # Use actual database location
    db_path = '/home/aiadmin/web-davy-code-scanner/backend/scans.db'

    if not os.path.exists(db_path):
        print(f"Database not found: {db_path}")
        return

    print(f"Exporting from: {db_path}")
    print(f"Output file: {output_file}")

    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # Get all table names
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;")
    all_tables = [row[0] for row in cursor.fetchall()]

    print(f"\nFound {len(all_tables)} tables")
    print("Config tables to export:", CONFIG_TABLES)

    with open(output_file, 'w') as f:
        f.write("-- Database Schema and Configuration Export\n")
        f.write("-- Generated by export_schema_and_config.py\n")
        f.write("-- Contains: Full schema + config tables only (no scan data)\n\n")

        # Export full schema for all tables
        f.write("-- ==========================================\n")
        f.write("-- SCHEMA (CREATE TABLE statements)\n")
        f.write("-- ==========================================\n\n")

        for table in all_tables:
            cursor.execute(f"SELECT sql FROM sqlite_master WHERE type='table' AND name='{table}';")
            result = cursor.fetchone()
            if result:
                create_sql = result[0]
                f.write(f"{create_sql};\n\n")

        # Export indexes
        f.write("-- ==========================================\n")
        f.write("-- INDEXES\n")
        f.write("-- ==========================================\n\n")

        cursor.execute("SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL;")
        for row in cursor.fetchall():
            f.write(f"{row[0]};\n")

        f.write("\n")

        # Export data for config tables only
        f.write("-- ==========================================\n")
        f.write("-- CONFIGURATION DATA\n")
        f.write("-- ==========================================\n\n")

        for table in CONFIG_TABLES:
            if table not in all_tables:
                print(f"  Skipping {table} (doesn't exist)")
                continue

            # Get row count
            cursor.execute(f"SELECT COUNT(*) FROM {table};")
            count = cursor.fetchone()[0]

            if count == 0:
                print(f"  {table}: 0 rows (skipped)")
                continue

            print(f"  {table}: {count} rows")

            f.write(f"-- Table: {table} ({count} rows)\n")

            # Get column names
            cursor.execute(f"PRAGMA table_info({table});")
            columns = [row[1] for row in cursor.fetchall()]

            # Export data
            cursor.execute(f"SELECT * FROM {table};")
            rows = cursor.fetchall()

            for row in rows:
                # Build INSERT statement
                values = []
                for val in row:
                    if val is None:
                        values.append('NULL')
                    elif isinstance(val, str):
                        # Escape single quotes
                        escaped = val.replace("'", "''")
                        values.append(f"'{escaped}'")
                    elif isinstance(val, bytes):
                        # Skip binary data
                        values.append('NULL')
                    else:
                        values.append(str(val))

                cols_str = ', '.join(columns)
                vals_str = ', '.join(values)
                f.write(f"INSERT INTO {table} ({cols_str}) VALUES ({vals_str});\n")

            f.write("\n")

    conn.close()

    print(f"\n✅ Export complete: {output_file}")
    print(f"   - Full schema for all tables")
    print(f"   - Data for {len([t for t in CONFIG_TABLES if t in all_tables])} config tables")
    print(f"   - Scan data excluded (use for fresh installs)")

if __name__ == '__main__':
    output_file = sys.argv[1] if len(sys.argv) > 1 else 'backend/init_db.sql'
    export_schema_and_config(output_file)
